### ISSUE TITLE
Some icons do not display in the KDE Plasma overview.

### ISSUE THREAD

**Issue by AxerTheAxe** [dreifacherspass/cyberpunk-technotronic-icon-theme#11]
Hello, I have noticed that some applications use their default icon when viewed from Plasma's desktop overview. The desktop files all use the correct icon and are displayed correctly everywhere else that I have checked. I am unsure if this is something on the application side that cannot be fixed by the icon set so apologies for any time wasted if that is the case. Once again thank you for the amazing icons.

Examples of the undesired behavior:
![def-icons](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/ca1b7818-0ac3-4903-b53a-0a3d03dea359)

The expected behavior:
![theme-icons](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/5fb45aff-fd52-4cc0-a047-a98ef33b50ba)

**Comment by dreifacherspass** [comment]
Hello! I reproduced the issue.

I tried some things and read a bit of the Plasma source code but I didn't find a solution to achieve the expected behaviour. The same also happens on GNOME. Maybe it's the way those specific apps are coded.

The only difference on my desktop is that OBS and  LMMS use the icons from the cyberpunk-technotronic icon theme. If you want to look further into it, just tell me what your OS is and the way you installed OBS and LMMS (distro repo, appimage etc...)

**Comment by AxerTheAxe** [comment]
> Hello! I reproduced the issue.
> 
> I tried some things and read a bit of the Plasma source code but I didn't find a solution to achieve the expected behaviour. The same also happens on GNOME. Maybe it's the way those specific apps are coded.
> 
> The only difference on my desktop is that OBS and LMMS use the icons from the cyberpunk-technotronic icon theme. If you want to look further into it, just tell me what your OS is and the way you installed OBS and LMMS (distro repo, appimage etc...)

Hello! I was just checking to see if this was an issue with the icon set itself. The issue doesn't bother me too much so I wouldn't worry about it. I will look through some of Plasma's source code as well to see if I notice anything. Thanks!

Feel free to close this issue.

**Comment by dreifacherspass** [comment]
You are welcome! Thank you for your input!
